### ISSUE TITLE
Cannot retrieve first credential

### ISSUE THREAD

**Issue by barakaki** [justin-ho/passwd-mng#41]
Complete these steps before submitting the issue.

- [ ] Assign the relevant Labels
- [ ] Assign the applicable Milestone
- [ ] Assign to the appropriate person

### Description
@ElliotIto 
There's also another problem when you try and get the credentials, it cannot be found. This only happens for the first credential being added. If you were to add two, facebook and myspace (in that order), it can't get facebook. I don't know if this has something to do with the getting key or the encryption.

### Steps to reproduce
1. start the application for the first time(no .eta file and storage file)
2. create a new password
3. add credentials
4. quit the program
5. re log in
6. get credentials

### Expected behavior
should get back all credentials being added.

**Comment by ElliotIto** [comment]
@barakaki Which branch. I am going to be checking all of them....

**Comment by ElliotIto** [comment]
@barakaki I checked all posted branches (except issue_21-enc, readme, and enc-file) and there are no issues. Have you pushed any changes that you have made to the branch you are working on to GitHub?

**Comment by barakaki** [comment]
Yeah I'm working on branch 34

**Comment by ElliotIto** [comment]
Have you pushed any changes that you have made, because as I said, I have no problems with accessing. I am using the latest updates that were pushed to Github.

**Comment by barakaki** [comment]
I made some pushes last night.

**Comment by justin-ho** [comment]
@barakaki have you deleted your storage.enc file recently? If we made any changes (which i think we did) to the way we read and write from the storage.enc file or the way it's stored, this could be causing your issue (old format vs new format).

**Comment by justin-ho** [comment]
hmm I am seeing the issue as well on the issue_34 branch.

**Comment by ElliotIto** [comment]
Is this Windows or Linux or Both?

**Comment by justin-ho** [comment]
I tested on Linux, but brandon is likely on windows so probably both.

**Comment by ElliotIto** [comment]
Are the steps done exactly the same? Since I am doing it and I can't replicate on Linux (Fedora).

**Comment by barakaki** [comment]
Does it have something to do with my update function? That's the only thing
I added that would be different in the encrypted class

**Comment by ElliotIto** [comment]
can you provide the output of the storage.enc file?

**Comment by justin-ho** [comment]
[storage.enc.zip](https://github.com/justin-ho/passwd-mng/files/405775/storage.enc.zip)

**Comment by ElliotIto** [comment]
The issue appears to be from the way the program is writing the output of the file. This can be fixed by changing line 35 in fileManipulator.py from ` if i >= total_count:` to 'if i > total_count - 1'

However, this is a separate issue from another one that I found with the update function.

We are just going to roll back to my update to the branch and see if there are any issues from there as the current update function is completely broken because of the method the file is written.

There are 2 dictionary that are being used by the program:
decrypted_list  (used for the user when getting/setting/updating information)
encoded_info (used when reading and writing to the file)

When the add_information is called, it is adding a NEW entry into the encoded_info dictionary - this results in a "duplicate" entry in the output of the file. This was why I had created a new function called update_information that replaces the entry with the updated information. The duplicate (new) entry would override the "old" entry when the file is being read, but I am getting an error when writing out to file from an update- so I am unable to test this theory.

At this point, I am confused as to why it worked for me after I had done a pull as I now get errors in python when I do the same test 5 hours ago....

**Comment by ElliotIto** [comment]
Okay, I found a different fix that resolves both issues (the line 35 fix and my errors). This will not resolve the bug of having both the old and new user information.

Line 35 would be changed to the following: `if "\n" not in encoded_info.get(i):`

This would ensure that when the line is written, only for data that do not have the \n character will get a \n character printed to separate the data.

**Comment by ElliotIto** [comment]
I would leave the decision up to both of you if you want to keep the way the data is written or revert back to my update. In either case the line 35 fix should be applied.

**Comment by barakaki** [comment]
Everything works perfectly now. Thank you. so if we revert it back, its going to use the add user function in the update and if we keep it now its going to use the update function thats in the encryptedfileeditor class right?

**Comment by ElliotIto** [comment]
@barakaki Do a push for what you have working, I can pull it and the changes to make it so that the old information is not being stored. Looking at the branch update I did, I was missing some changes that I didn't push...In effect, it will not be using the add_user function - I had missed a push that had included the update function that I had created. 

Basically the update that I had done had screwed up on the pass-mgr.py side and had everything else on the backend built.

**Comment by barakaki** [comment]
Oks I'll do a push and I'll let u know after when I did it

**Comment by barakaki** [comment]
Ok I pushed what I got

**Comment by ElliotIto** [comment]
Thanks, I am working on the fix. Running into a weird duplication issue but should be done soon.

**Comment by barakaki** [comment]
Thanks!

**Comment by ElliotIto** [comment]
Okay did a push with the fix.
